'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'StronglyTypedResourceBuilder generó automáticamente esta clase
    'a través de una herramienta como ResGen o Visual Studio.
    'Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    'con la opción /str o recompile su proyecto de VS.
    '''<summary>
    '''  Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Controladores.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        '''  búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property anterior() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("anterior", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Byte[].
        '''</summary>
        Friend ReadOnly Property audio() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("audio", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a de vuelta al infierno en el fuego eterno
        '''me voy derecho hacia el tacho
        '''me empacho y me escracho
        '''pierdo la calma, yo ya no juego más
        '''ruego por tu alma
        '''no se donde estás
        '''y pierdo el paso
        '''mientras repaso el caso
        '''que no era broma me quedo en coma
        '''ahora solo hablo otro idioma
        '''no toma más que un segundo
        '''yo no me desbundo
        '''no puedo saber que pedo
        '''si me enredo en la alfombra
        '''no me da risa la ceniza
        '''que se lleva el viento
        '''como los presos de golpe bajo
        '''yo me hice de abajo
        '''no intento escapar yo no me  [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend ReadOnly Property cablepelado() As String
            Get
                Return ResourceManager.GetString("cablepelado", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a i go down to the esquina
        '''to meet the barra
        '''have a par de vinos
        '''and play some funky guitarra
        '''los guachos le rezan a santa teresa en caja,
        '''miro la baraja me prendo al vaso
        '''nunca más digo paso pero algo no encaja
        '''justo ahí me metí donde no debía
        '''yo no quería tanta porquería
        '''solo espero despacio un suceso
        '''como un preso
        '''que siente el pecho estrecho y sabe que
        '''ya no puede caminar derecho
        '''como un punchinbol espiritual, emocional
        '''si es tinto lija me lo tomo igual
        '''subo el codo estoy rígido del todo
        '''s [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend ReadOnly Property camabionica() As String
            Get
                Return ResourceManager.GetString("camabionica", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a como una enfermedad
        '''una hecatombe termonuclear
        '''te puedo hacer sentir bien
        '''animal anormal, un problema terminal
        '''te puedo ver dormir hacer sufrir
        '''hasta más no pedir
        '''puedo tocarte o asesinarte
        '''solamente por amor al arte
        '''puedo ser tu peor pesadilla
        '''tu nieve de fresa,
        '''un montón de pastillas tranquilizantes
        '''puedo darte para adelante
        '''dejarte en calma si
        '''te duele la barriga
        '''cuando el veneno que puse en tu vaso
        '''te deje boca arriba
        '''y me pidas por favor
        '''que tu día termine mejor
        '''tratame como un crimin [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend ReadOnly Property criminal() As String
            Get
                Return ResourceManager.GetString("criminal", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a pienso denso
        '''me siento algo tenso
        '''la mera neta no soy juan d&apos;arienzo
        '''tampoco pichuco
        '''no me machuco si te digo que
        '''parado en la cancha
        '''me siento a mis anchas
        '''me meten una plancha
        '''revancha es lo
        '''que
        '''pido pero no
        '''solo me parten la
        '''rodilla
        '''parece una astilla
        '''se quiebra me enhebra y me
        '''recuerda que
        '''no me gusta el fainá si no viene de orilla
        '''como roger milla
        '''aunque tengo mis años
        '''te puedo hacer más de dos caños
        '''no es extraño
        '''algún rené higuita
        '''siempre va a haber
        '''tenés que entender que no va [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend ReadOnly Property denso() As String
            Get
                Return ResourceManager.GetString("denso", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Medium list
        '''Client list
        '''Place list
        '''User list
        '''New preload
        '''New Client
        '''New place
        '''Zones list
        '''Batch list
        '''Vehicle list
        '''New batch
        '''New vehicle
        '''Incorrect credentials. Try again.
        '''This application is only for {0}
        '''The Login class has not been set up correctly
        '''Connected
        '''Disconnected
        '''Username
        '''Password
        '''Log in
        '''Forgot password
        '''Set up network
        '''State:
        '''Designed by
        '''Home
        '''About
        '''My profile
        '''Log out
        '''Make
        '''Model
        '''Client
        '''Year
        '''Type
        '''Zone
        '''Subzone
        '''Sub zone
        '''Place
        '''Position
        '''Batch
        '''Save code
        '''Read more
        '''Show [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend ReadOnly Property English() As String
            Get
                Return ResourceManager.GetString("English", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Lista de mídia
        '''Listar Clientes
        '''Listar locais
        '''Listar Usuário
        '''Novo pré-carregamento
        '''Novo Cliente
        '''Lugar novo
        '''Lista de zonas
        '''Lista de lotes
        '''Lista de Veículos
        '''Lote novo
        '''Veículo novo
        '''Credenciais ruins Tente novamente
        '''Este aplicativo é apenas para {0}
        '''Classe de login não definida corretamente
        '''Conectado
        '''Desconectado
        '''Nome de usuário
        '''Senha
        '''Entrar
        '''Restaurar
        '''Configurar rede
        '''Estado:
        '''Desenhado por
        '''Página inicial
        '''Sobre
        '''Minha conta
        '''Fechar Sessão
        '''Marca
        '''Modelo
        '''Cliente
        '''Ano
        '''Tipo
        '''Zona
        '''Subzona
        ''' [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend ReadOnly Property French() As String
            Get
                Return ResourceManager.GetString("French", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a escupo la bandera
        '''me toco la manguera
        '''quedo afuera
        '''no pienso en la manera
        '''de volver a entrar
        '''nada en particular
        '''just thru the window
        '''te agarro y te pringo
        '''con mi ñoqui juega ese yupi
        '''mientras una grupi le saca el queso
        '''por eso me quedo de pie
        '''miro la tevé
        '''ahí ya no están
        '''ni martín karadagián
        '''ni el gran satán hussein
        '''solamente el nieto de kwai chang cain
        '''que francamente
        '''no lo hace muy biein
        '''I gotta make it happen
        '''aunque puede que me maten
        '''cause i&apos;ve been here
        '''and i&apos;ve been there i&apos;m goin [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend ReadOnly Property guacho() As String
            Get
                Return ResourceManager.GetString("guacho", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property iconoF() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iconoF", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property info() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("info", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Inicio() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Inicio", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a miro veo creo
        '''que me mareo y caigo
        '''hacia atrás
        '''no da para más
        '''cuento del cero hasta el diez
        '''no ves que esta todo al revés
        '''rose nylon
        '''no es lord byron
        '''no me gusta que te estires la ropa
        '''callate la boca esa roca
        '''puede ser para vos
        '''bruce willys no es mi dios
        '''y aunque me gustó die hard
        '''it&apos;s hard to be dying
        '''i don&apos;t know a fuck about freestyling
        '''cos i&apos;m lying on the floor
        '''let&apos;s open the door
        '''and take a look inside
        '''my name is not luca
        '''no seas hijo de puta
        '''como te gusta sumo la hago corta
        '''y au [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend ReadOnly Property lmental() As String
            Get
                Return ResourceManager.GetString("lmental", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Icon similar a (Icono).
        '''</summary>
        Friend ReadOnly Property logo() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("logo", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property logo1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logo1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a es inútil pedir que te quedes a dormir
        '''para que insistir
        '''yo se que vos preferís el aliento
        '''de un guarda de bondi grasiento o
        '''de mierda una vieja
        '''que te arranca la oreja
        '''con tal de sacarte el asiento
        '''es un hecho que todavía
        '''no apareció el tipo recio
        '''que de con tu precio y te saque de la vía
        '''mejor me fumo un rocket y como sony crockett
        '''te doy el alto y te digo
        '''manos arriba guey
        '''adonde crees que ibas si aquí está la ley
        '''no podés ser el hombre nuclear
        '''si todavía no tenés celular
        '''como el manco de [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend ReadOnly Property maldelacabeza() As String
            Get
                Return ResourceManager.GetString("maldelacabeza", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property notificacion() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("notificacion", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ojo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ojo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ojo_no() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ojo_no", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a montevideo no es l.a. city
        '''ni vos sos negro, chicano o inmigrante
        '''por eso toda la basura que decís
        '''me resbala por la parte de adelante
        '''el concurso del champión más rapero,
        '''guacho pajero
        '''me chupa un huevo
        '''yo soy del buceo y te lo digo de nuevo
        '''un huevo eso me chupa un huevo
        '''yo no hablo ni de perra ni de puta
        '''si sos tan macho limpiátelo con viruta
        '''nada más
        '''que la mitad de las cosas que digo tienen sentido
        '''y del resto me olvido
        '''no me pidas que me calle
        '''porque hay un detalle
        '''que te comiste y por [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend ReadOnly Property perkins() As String
            Get
                Return ResourceManager.GetString("perkins", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a mejor llama a tu psicoterapeuta
        '''mejor llama a tu psicoterapeuta
        '''si son cucumelos comelos
        '''masticalos tragalos despedazalos
        '''rompete la cabeza
        '''dátela contra la mesa
        '''hacete un favor
        '''y enrolate en la legión extranjera
        '''desde hoy hasta el día que te mueras
        '''bueno fuera
        '''marcón
        '''tomate un te de floripón
        '''porque no dejas de pensar
        '''en saltar en gritar
        '''se te tuerce la boca escupís al hablar
        '''partite los dientes
        '''avisale a tus parientes
        '''contales que sos
        '''de donde venís
        '''que cosas haces cuando no estas acá
        '''t [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend ReadOnly Property psicoterapeuta() As String
            Get
                Return ResourceManager.GetString("psicoterapeuta", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property sigiente() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sigiente", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property sinContenidoFotografico() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sinContenidoFotografico", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Lista de medios
        '''Listar Clientes
        '''Listar Lugares
        '''Listar Usuario
        '''Nueva Precarga
        '''Nuevo Cliente
        '''Nuevo Lugar
        '''Lista zonas
        '''Lista lotes
        '''Lista vehiculos
        '''Nuevo lote
        '''Nuevo vehiculo
        '''Credenciales incorrectas. Intente nuevamente
        '''Esta aplicacion es unicamente para los {0}
        '''No se ha configurado correctamente la clase de login
        '''Conectado
        '''Desconectado
        '''Nombre de usuario
        '''Contraseña
        '''Ingresar 
        '''Restaurar
        '''Configurar red
        '''Estado:
        '''Diseñado por
        '''Inicio
        '''Acerca de
        '''Mi cuenta
        '''Cerrar sesión
        '''Marca
        '''Modelo
        '''Cliente
        '''A [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend ReadOnly Property Spanish() As String
            Get
                Return ResourceManager.GetString("Spanish", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property texto() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("texto", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Uruguay UR gay
        '''you better go your way
        '''estas enfermo y no ves
        '''que siete y tres
        '''nunca da diez
        '''heces todo al revés y
        '''estas equivocado
        '''desde la cabeza hasta los pies
        '''vas a bailar hasta reventar
        '''vas a intoxicarte tomando mejoral
        '''no hay nada de malo
        '''tampoco de bueno
        '''demasiadas curvas y no tenés frenos
        '''such is life in a tropical country
        '''such is life en el trópico
        '''such is life in a tropical country
        '''such is life en Uruguay
        '''que cobras
        '''juez
        '''prepará tu pasaje
        '''y tené listo el equipaje
        '''pero no me mir [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend ReadOnly Property urgay() As String
            Get
                Return ResourceManager.GetString("urgay", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property user() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("user", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
