#!/bin/bash
carpeta="/var/automotora"
echo "Ingrese la ruta de la carpeta base de instalacion o presione enter para usar la por defecto"
read vartemp
if [ -n "$vartemp" ]
then
carpeta="$vartemp"
fi
mkdir $carpeta
cd $carpeta
mkdir Backups Temp Registro
cd Registro
touch FechasUsuario
echo ":UID:FechaCreacion:FechaEliminacion">>FechasUsuario

#Variables del entorno
echo "export carpetaBase=$carpeta">>/etc/profile
source /etc/profile

